name: Merge Check via Shared Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  check-merge:
    uses: tu-org/workflows/.github/workflows/merge-tracker.yaml@master
    with:
      expected-users: ${{ vars.EXPECTED_USERS }}
