name: Merge Check via Shared Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  check-merge:
    uses: ai-somorrostro/workflows/.github/workflows/merge-tracker.yaml@master
    secrets:
      GH_TOKEN: ${{ secrets.PAT_FOR_WORKFLOW }}
